"""Lexical store — DuckDB FTS (BM25). Same file, same connection as `DocStore`.

Why a lexical channel at all:
  Medical retrieval lives and dies on exact tokens — drug names ("olaparib"), gene symbols
  ("BRCA1"), trial identifiers ("NCT03402841"), dosages ("300 mg"), KB numbers. Dense vectors
  blur these into their neighbourhood; BM25 matches them verbatim. This is the third RRF
  channel promised in ADR-0006 and drawn in the architecture diagram.

Why DuckDB FTS (no new dependency):
  The inverted index lives in the same `.duckdb` file as the chunk text it indexes — one file,
  one backup. `PRAGMA create_fts_index` builds it; the generated `fts_main_chunks.match_bm25`
  macro scores documents against a query.

Snapshot caveat:
  DuckDB's FTS index is a *snapshot*, not auto-updating — new chunks are invisible until the
  index is rebuilt. The ingest pipeline calls `rebuild()` after each run; `search()` also
  lazily builds the index on first use so an already-populated corpus is searchable immediately.

Tokenizer note:
  The default `ignore` regex strips every non-letter, which would delete digits — fatal for
  medical text full of dosages, years, and identifiers. We override it to keep `[0-9]`.
"""

from __future__ import annotations

from medground.store.docs import DocStore

# Generated by `create_fts_index('chunks', ...)`: schema `fts_main_<table>`, macro `match_bm25`.
FTS_SCHEMA = "fts_main_chunks"


class LexicalStore:
    """DuckDB FTS (BM25) over the `chunks.text` column. Shares the DocStore connection."""

    def __init__(self, docs: DocStore | None = None) -> None:
        self.docs = docs or DocStore()
        self._loaded = False

    def _ensure(self) -> None:
        """Idempotent: install + load the `fts` extension on this connection."""
        if self._loaded:
            return
        c = self.docs.conn
        c.execute("INSTALL fts")
        c.execute("LOAD fts")
        self._loaded = True

    def indexed(self) -> bool:
        """True if the FTS index has been built (its generated schema exists)."""
        self._ensure()
        row = self.docs.conn.execute(
            "SELECT count(*) FROM information_schema.schemata WHERE schema_name = ?",
            [FTS_SCHEMA],
        ).fetchone()
        return bool(row and int(row[0]) > 0)

    # ----- writes -----

    def rebuild(self) -> int:
        """(Re)build the inverted index over `chunks.text`. Returns #chunks indexed.

        `ignore` keeps digits (default would drop them); `overwrite=1` makes this idempotent.
        Cheap — the text is already resident in DuckDB; this is just an inverted-index pass.
        """
        self._ensure()
        c = self.docs.conn
        n = int(c.execute("SELECT count(*) FROM chunks").fetchone()[0])
        if n == 0:
            return 0
        # Raw string so the regex reaches DuckDB verbatim (DuckDB strings don't C-unescape).
        c.execute(
            r"""
            PRAGMA create_fts_index(
                'chunks', 'id', 'text',
                stemmer = 'porter',
                stopwords = 'english',
                ignore = '(\.|[^a-z0-9])+',
                strip_accents = 1,
                lower = 1,
                overwrite = 1
            )
            """
        )
        # Flush immediately. `create_fts_index(overwrite=1)` drops + recreates the fts_main_chunks
        # schema; if that op is left only in the WAL and the process is then killed, WAL replay
        # fails ("Cannot drop fts_main_chunks ... terms depends on it" — replay has no CASCADE),
        # making the whole DB unopenable. Checkpointing materialises it into the main file.
        c.execute("CHECKPOINT")
        return n

    # ----- reads -----

    def search(self, query: str, k: int = 8) -> list[dict]:
        """Top-k chunks by BM25, joined with chunk + paper metadata for grounding.

        Self-healing: if the index is missing but chunks exist, build it once. Returns `_bm25`
        (the raw, unbounded BM25 score) alongside citation fields in one round trip.
        """
        q = (query or "").strip()
        if not q:
            return []
        if not self.indexed() and self.rebuild() == 0:
            return []
        rows = self.docs.conn.execute(
            f"""
            SELECT c.id AS id,
                   c.paper_id,
                   c.section,
                   c.text,
                   c.index AS chunk_index,
                   p.title,
                   p.year,
                   p.journal,
                   p.url,
                   s.score AS _bm25
            FROM (
                SELECT id, {FTS_SCHEMA}.match_bm25(id, ?) AS score FROM chunks
            ) s
            JOIN chunks c ON c.id = s.id
            JOIN papers p ON p.id = c.paper_id
            WHERE s.score IS NOT NULL
            ORDER BY s.score DESC
            LIMIT ?
            """,
            [q, k],
        ).fetchall()
        cols = [d[0] for d in self.docs.conn.description]
        return [dict(zip(cols, r, strict=False)) for r in rows]

    def count(self) -> int:
        """Number of documents currently in the index (0 if not built)."""
        if not self.indexed():
            return 0
        try:
            return int(
                self.docs.conn.execute(f"SELECT count(*) FROM {FTS_SCHEMA}.docs").fetchone()[0]
            )
        except Exception:
            return 0


def open_lexical(docs: DocStore | None = None) -> LexicalStore:
    return LexicalStore(docs=docs)
